#!/usr/bin/env bash
# This script prints Best School 10 times and Hi on the 9th iteration
i=1
while [ $i -le 10 ]
do
printf "Best School\n"
if [ $i -eq 9 ]
then
printf "Hi\n"
fi
i=$((i + 1))
done
