#!/usr/bin/env bash
# This script checks the properties of the file named school
if [ -e school ]; then
    printf "school file exists\n"
    if [ ! -s school ]; then
        printf "school file is empty\n"
    else
        printf "school file is not empty\n"
    fi
    if [ -f school ]; then
        printf "school is a regular file\n"
    fi
else
    printf "school file does not exist\n"
fi
